"""
VoicePath AI — Flask Backend API
Disease Detection via Voice Analysis + Patient Auth
"""
import os, sys, json, time, traceback
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from flask import Flask, request, jsonify, send_from_directory, session
from flask_cors import CORS
from database import db, User, Patient, VoiceResult
from auth import auth_bp

app = Flask(__name__, static_folder='../frontend', static_url_path='')
app.secret_key = 'voicepath-ai-secret-key-2024-change-in-production'
# Use /tmp on Vercel serverless; local path otherwise
_db_path = os.environ.get('DATABASE_URL') or \
    'sqlite:///' + os.path.join(os.environ.get('VERCEL') and '/tmp' or os.path.dirname(__file__), 'voicepath.db')
app.config['SQLALCHEMY_DATABASE_URI'] = _db_path
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'
app.config['PERMANENT_SESSION_LIFETIME'] = 86400 * 7   # 7 days

CORS(app, supports_credentials=True)
db.init_app(app)
app.register_blueprint(auth_bp)

UPLOAD_DIR  = os.path.join(os.path.dirname(__file__), 'uploads')
RESULTS_DIR = os.path.join(os.path.dirname(__file__), 'results')
for _d in [UPLOAD_DIR, RESULTS_DIR,
           os.path.join(os.path.dirname(__file__), 'models', 'saved'),
           os.path.join(os.path.dirname(__file__), 'static_downloads')]:
    os.makedirs(_d, exist_ok=True)

ALLOWED_EXTS = {'.wav', '.mp3', '.ogg', '.flac', '.m4a', '.webm'}
DISEASE_NAMES = {
    'parkinsons':  "Parkinson's Disease",
    'respiratory': 'Respiratory Disease',
    'alzheimers':  "Alzheimer's Disease",
    'als':         'ALS (Motor Neuron Disease)',
    'depression':  'Depression',
}

def allowed_file(filename):
    return os.path.splitext(filename.lower())[1] in ALLOWED_EXTS


with app.app_context():
    db.create_all()


@app.route('/')
def index():
    return send_from_directory(app.static_folder, 'index.html')


@app.route('/login')
@app.route('/register')
@app.route('/dashboard')
def spa_routes():
    return send_from_directory(app.static_folder, 'index.html')


@app.route('/api/health', methods=['GET'])
def health():
    models_dir = os.path.join(os.path.dirname(__file__), 'models', 'saved')
    trained = [d for d in ['parkinsons','respiratory','alzheimers','als','depression']
               if os.path.exists(os.path.join(models_dir, f'{d}_model.pkl'))]
    user_count = User.query.count()
    return jsonify({'status': 'ok', 'trained_models': trained,
                    'registered_users': user_count, 'timestamp': time.time()})


@app.route('/api/diseases', methods=['GET'])
def list_diseases():
    models_dir = os.path.join(os.path.dirname(__file__), 'models', 'saved')
    diseases = []
    for key, name in DISEASE_NAMES.items():
        model_ready = os.path.exists(os.path.join(models_dir, f'{key}_model.pkl'))
        result_file = os.path.join(RESULTS_DIR, f'{key}_results.json')
        result = {}
        if os.path.exists(result_file):
            with open(result_file) as f:
                result = json.load(f)
        diseases.append({'key': key, 'name': name, 'model_ready': model_ready,
                         'best_model': result.get('best_model', 'N/A'),
                         'metrics': result.get('best_result', {})})
    return jsonify({'diseases': diseases})


@app.route('/api/predict', methods=['POST'])
def predict_route():
    uid = session.get('user_id')

    if 'audio' not in request.files:
        return jsonify({'error': 'No audio file uploaded'}), 400

    disease = request.form.get('disease', '').lower().strip()
    if not disease or disease not in DISEASE_NAMES:
        return jsonify({'error': f'Invalid disease. Choose: {list(DISEASE_NAMES.keys())}'}), 400

    f = request.files['audio']
    if not f.filename or not allowed_file(f.filename):
        return jsonify({'error': 'Invalid file type. Upload WAV, MP3, OGG, or FLAC.'}), 400

    ext = os.path.splitext(f.filename.lower())[1]
    save_path = os.path.join(UPLOAD_DIR, f'predict_{int(time.time())}{ext}')
    f.save(save_path)

    try:
        from prediction.predict import predict
        result = predict(save_path, disease)
        result['disease_name'] = DISEASE_NAMES[disease]
        result['status'] = 'success'
        result['disclaimer'] = (
            'This result is generated by an experimental AI model for research purposes only. '
            'It does not constitute a medical diagnosis. Consult a qualified healthcare professional.'
        )

        # Save to DB if user is logged in
        if uid:
            vr = VoiceResult(
                user_id=uid, disease=disease,
                label=result.get('label'), label_name=result.get('label_name'),
                confidence=result.get('confidence'), uncertain=result.get('uncertain', False),
                features=json.dumps(result.get('top_features', {}))
            )
            db.session.add(vr)
            db.session.commit()
            result['saved_to_history'] = True

        return jsonify(result)
    except FileNotFoundError as e:
        return jsonify({'error': str(e), 'status': 'model_not_trained'}), 503
    except Exception as e:
        traceback.print_exc()
        return jsonify({'error': f'Analysis failed: {str(e)}', 'status': 'error'}), 500
    finally:
        try:
            os.remove(save_path)
        except Exception:
            pass


@app.route('/api/history', methods=['GET'])
def get_history():
    uid = session.get('user_id')
    if not uid:
        return jsonify({'error': 'Not authenticated'}), 401
    results = (VoiceResult.query.filter_by(user_id=uid)
               .order_by(VoiceResult.created_at.desc()).limit(50).all())
    return jsonify({'history': [r.to_dict() for r in results]})


@app.route('/api/results/<disease>', methods=['GET'])
def get_results(disease):
    result_file = os.path.join(RESULTS_DIR, f'{disease}_results.json')
    if not os.path.exists(result_file):
        return jsonify({'error': 'Results not found. Train model first.'}), 404
    with open(result_file) as f:
        return jsonify(json.load(f))


@app.route('/api/admin/users', methods=['GET'])
def admin_users():
    uid = session.get('user_id')
    if not uid:
        return jsonify({'error': 'Not authenticated'}), 401
    user = db.session.get(User, uid)
    if not user or user.role != 'admin':
        return jsonify({'error': 'Admin access required'}), 403
    users = User.query.all()
    return jsonify({'users': [u.to_dict() for u in users]})


@app.route('/api/download/datasets', methods=['GET'])
def download_datasets():
    """Download the full human voice dataset ZIP."""
    zip_path = os.path.join(os.path.dirname(__file__), 'static_downloads', 'human_voice_datasets.zip')
    if not os.path.exists(zip_path):
        return jsonify({'error': 'Dataset ZIP not found'}), 404
    from flask import send_file
    return send_file(zip_path, as_attachment=True,
                     download_name='VoicePath_AI_Human_Voice_Datasets.zip',
                     mimetype='application/zip')


@app.route('/api/download/dataset/<disease>', methods=['GET'])
def download_single_dataset(disease):
    """Download a single disease dataset as pre-built ZIP."""
    valid = {'respiratory', 'alzheimers', 'als', 'depression'}
    if disease not in valid:
        return jsonify({'error': f'Unknown disease: {disease}'}), 400
    dl_dir = os.path.join(os.path.dirname(__file__), 'static_downloads')
    fname = f'{disease}_dataset.zip'
    if not os.path.exists(os.path.join(dl_dir, fname)):
        return jsonify({'error': 'Dataset ZIP not found on server'}), 503
    from flask import send_from_directory
    return send_from_directory(dl_dir, fname, as_attachment=True,
                               download_name=f'VoicePath_{disease}_dataset.zip',
                               mimetype='application/zip')


@app.errorhandler(404)
def not_found(e):
    return send_from_directory(app.static_folder, 'index.html')


if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"VoicePath AI Backend starting on http://0.0.0.0:{port}")
    app.run(host='0.0.0.0', port=port, debug=False)
